info:
  application:
    name: @project.name@
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
    description: @project.description@

spring:
  application:
    name: ${info.application.name}
  profiles:
    active: homepage

logging:
  level:
    de:
      rahn:
        net:
          proxy:
            sllproxy:
              config: debug

#server:
#  ssl:
#    key-store: classpath:keystore.jks
#    key-store-password: 1234abc
#    key-alias: localhost
#    key-password: 1234abc
#    trust-store: classpath:truststore.jks
#    trust-store-password: 1234abc
#    client-auth: need

---

spring:
  profiles: homepage
server:
  port: 8080
zuul:
  routes:
    homepage:
      path: /**
      url: https://www.frank-rahn.de/

---

spring:
  profiles: proxy
server:
  port: 8443
zuul:
  routes:
    proxy:
      path: /**
      url: http:localhost:8080
