info:
  application:
    name: @project.name@
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
    description: @project.description@

spring:
  application:
    name: ${info.application.name}
  profiles:
    active: homepage
  jackson:
    serialization:
      indent-output: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    de:
      rahn:
        net:
          proxy:
            tlsproxy:
              config: debug
    org:
      springframework:
        cloud:
          gateway: debug

#server:
#  ssl:
#    key-store: classpath:keystore.jks
#    key-store-password: ${key-store-password}
#    key-alias: ${server}
#    key-password: ${key-password}
#    trust-store: classpath:truststore.jks
#    trust-store-password: ${key-store-password}
#    client-auth: want

---

spring:
  profiles: homepage
  cloud:
    gateway:
      routes:
        - id: homepage
          uri: https://www.frank-rahn.de/
          predicates:
            - Path=/**
          filters:
            - RemoveRequestHeader=Cookie
            - RemoveResponseHeader=Set-Cookie
server:
  port: 8080

---

spring:
  profiles: proxy
  cloud:
    gateway:
      routes:
        - id: proxy
          uri: http://localhost:8080
          predicates:
            - Path=/{segment}
server:
  port: 8443
