info:
  application:
    name: @project.name@
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
    description: @project.description@

spring:
  application:
    name: ${info.application.name}
  profiles:
    active: homepage

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    de:
      rahn:
        net:
          proxy:
            sllproxy:
              config: debug

server:
  ssl:
#    key-store: classpath:keystore.jks
#    key-store-password: ${key-store-password}
#    key-alias: ${server}
#    key-password: ${key-password}
#    trust-store: classpath:truststore.jks
#    trust-store-password: ${key-store-password}
    client-auth: want

---

spring:
  profiles: homepage
server:
  port: 8443
zuul:
  sensitive-headers: Cookie,Set-Cookie
  routes:
    homepage:
    path: /**
    url: https://www.frank-rahn.de/

---

spring:
  profiles: proxy
server:
  port: 8080
zuul:
  routes:
    proxy:
      path: /**
      url: http://localhost:8080
